name: Run Python Script Manually

on:
  workflow_dispatch:  # Chỉ chạy khi kích hoạt thủ công từ GitHub Actions

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install numpy pandas scikit-learn xgboost underthesea jupyterlab notebook ipykernel papermill openpyxl joblib

      - name: Run Python Script
        run: |
          python dlm_label.py

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Verify rclone Installation
        run: |
          rclone version

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

      - name: Upload large files to Google Drive
        run: |
          rclone copy model_550k.pkl ggdrive:/Data_Automate/ --progress
          rclone copy word_embeddings_550k.json ggdrive:/Data_Automate/ --progress

      - name: Commit and Push Small Output to GitHub
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://$GH_PAT@github.com/tuananhs702/DLL_Label.git
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Auto-update after running Python script"
            git push origin main
          else
            echo "No changes to commit"
          fi
